input {
	file {
		path => "/usr/share/logstash/logs/app.log"
		start_position => "beginning"
	}
}

filter {
	grok {
	match => { "message" = "%{TIMESTAMP ISO8601:timestamp} %{loglevel:level} %{GREEDYDATA:log_message}"}
	}
}

output {
	elasticsearch {
		hosts => ["http://elasticsearch:9200"]
		index => "app-logs-%{+YYYY.MM.dd}"
	}
}

