auth_enabled: false
server:
  http_listen_port: 3100

common:
  path_prefix: /temp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
       rules_directory: /tmp/loki/rules
    replication_factor: 1
    ring:
      instace_addr: 127.0.0.1
      kvstore:
        store: inmemory

