name: CI Simples 2

 on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest 
  steps:    
    -name: Baixar o codigo do Repositório 2
    uses: actions/checkout@v4    
    -name: Teste de Funcionamento 2
    run: echo "CI Funcionando no projeto INPE"
